# Generated by Django 5.0.4 on 2024-04-14 13:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("statements", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ApiResponse",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("mime_type", models.CharField(max_length=32)),
                ("content_sha", models.CharField(default="", max_length=40)),
                ("errors", models.CharField(max_length=2048, null=True)),
                ("response", models.BinaryField(null=True)),
                ("response_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "api_responses",
            },
        ),
        migrations.AddField(
            model_name="statement",
            name="api_response",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, to="statements.apiresponse"
            ),
        ),
    ]
