# Generated by Django 5.0.4 on 2024-05-17 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("statements", "0002_apiresponse_statement_api_response"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="apiresponse",
            table="ocr_api_responses",
        ),
        migrations.AlterModelTable(
            name="statement",
            table="ocr_statements",
        ),
    ]
