# Generated by Django 5.0.4 on 2024-05-17 07:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("statements", "0003_alter_apiresponse_table_alter_statement_table"),
    ]

    operations = [
        migrations.CreateModel(
            name="Transaction",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("trx_date", models.DateField(null=True)),
                ("account_num", models.TextField(max_length=12, null=True)),
                ("currency", models.TextField(null=True)),
                ("withdraw_amount", models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ("deposit_amount", models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ("balance", models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ("description", models.TextField(null=True)),
                ("raw_entity", models.BinaryField(null=True)),
                (
                    "statement",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transactions",
                        to="statements.statement",
                    ),
                ),
            ],
            options={
                "db_table": "ocr_transactions",
            },
        ),
    ]
